models.py
from flask_wtf import FlaskForm as Form
from wtforms import StringField,IntegerField,SubmitField
from wtforms import validators
from database import db


class Horse(db.Model):
    __tablename__ = 'horses'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    suit = db.Column(db.String(64), nullable=False)
    win_score = db.Column(db.Integer)
    jockey_id = db.Column(db.Integer, db.ForeignKey('jockeys.id'))

    participitions = db.relationship('Participition', backref="horse")


    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.remove(self)
        db.session.commit()

    def __repr__(self):
        return f"Лошадь(Кличка: {self.name}, {self.age} лет, {self.suit})"


class Jockey(db.Model):
    __tablename__ = 'jockeys'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    win_score = db.Column(db.Integer)

    participition = db.relationship('Participition', backref="jockey")
    horses = db.relationship('Horse')

    def __repr__(self):
        return f"Наездник(Имя: {self.name}, возраст {self.age})"

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.remove(self)
        db.session.commit()


class Competition(db.Model):
    __tablename__ = 'competitions'
    id = db.Column(db.Integer, primary_key=True)
    hippodrom_id = db.Column(db.Integer, db.ForeignKey('hippodroms.id'))
    date = db.Column(db.DATE, nullable=False)

    participitions = db.relationship("Participition", backref='competition')

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.remove(self)
        db.session.commit()

    def __repr__(self):
        return f"Competition({self.hippodrome.address},{self.hippodrome.name},{self.date})"


class Participition(db.Model):
    __tablename__ = 'participitions'
    place = db.Column(db.Integer, primary_key=True)
    horse_id = db.Column(db.Integer, db.ForeignKey('horses.id'), primary_key=True)
    jockey_id = db.Column(db.Integer, db.ForeignKey('jockeys.id'), primary_key=True)
    competition_id = db.Column(db.Integer, db.ForeignKey('competitions.id'), primary_key=True)


    def __repr__(self):
        return f"Partitipitions({self.horse};{self.jockey})"

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.remove(self)
        db.session.commit()


class Hippodrome(db.Model):
    __tablename__ = 'hippodroms'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), nullable=False)
    address = db.Column(db.String(64), nullable=False)

    participitions = db.relationship("Competition", backref='hippodrome')

    def __repr__(self):
        return f"{self.name}, {self.address}"

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.remove(self)
        db.session.commit()

forms.py
from flask_wtf import FlaskForm as Form
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms import StringField, IntegerField, SubmitField, DateField
from wtforms.validators import InputRequired, Length

from models import Jockey, Horse, Competition, Participition


def get_all_jockeys():
    return Jockey.query.all()


def get_all_horses():
    # return [horse for horse in Jockey.horses]
    return Horse.query.all()


def get_all_cometitions():
    return Competition.query.all()


class JockeyForm(Form):
    name = StringField('Имя')
    age = IntegerField('Возраст')
    submit = SubmitField('Submit')

    def save(self, request_method):
        if request_method == 'POST':
            name = self.name.data
            age = self.age.data
            Jockey.save(Jockey(name=name, age=age, win_score=0))


class HorseForm(Form):
    name = StringField('Имя')
    age = IntegerField('Возраст')
    jockey = QuerySelectField("Жокей", query_factory=get_all_jockeys)
    suit = StringField('Масть')
    submit = SubmitField('Submit')

    def save(self, request_method):
        if request_method == "POST":
            name = self.name.data
            age = self.age.data
            suit = self.suit.data
            jockey_id = self.jockey.data.id
            Horse.save(Horse(name=name, age=age, suit=suit, jockey_id=jockey_id, win_score=0))

    def __repr__(self):
        return f"HorseForm({self.name},{self.age},{self.submit})"


class ParticipationForm(Form):
    place = StringField('Место')
    horse = QuerySelectField('Лошадь', query_factory=get_all_horses)
    jockey = QuerySelectField('Жокей', query_factory=get_all_jockeys)
    competition = QuerySelectField('Соревнование', query_factory=get_all_cometitions)
    submit = SubmitField('Добавить')

    def save(self):
        place = self.place.data
        horse = self.horse.data
        jockey = self.jockey.data
        competition = self.competition.data
        Participition.save(
            Participition(place=place, horse_id=horse.id, jockey_id=jockey.id, competition_id=competition.id))


class FindByDateForm(Form):
    date = StringField('Дата', validators=[InputRequired(), Length(max=8, min=8)])
    find = SubmitField('Поиск')


class FindByHorseForm(Form):
    horse = QuerySelectField("Лошади", query_factory=get_all_horses)
    submit = SubmitField("Поиск")


class FindByJockeyForm(Form):
    jockey = QuerySelectField("Жокей", query_factory=get_all_jockeys)
    submit = SubmitField("Поиск")

views.py
from flask import Blueprint, render_template, request

from forms import HorseForm, JockeyForm, ParticipationForm, FindByDateForm, FindByHorseForm, FindByJockeyForm
from models import Horse, Jockey, Competition, Participition

page = Blueprint('page', __name__, template_folder='templates')


@page.route('/')
def home_page():
    return render_template("index.html")


@page.route('/horses', methods=['GET', 'POST'])
def horses():
    form = HorseForm(request.form)
    horses = Horse.query.all()
    form.save(request.method)
    return render_template('horses.html', horses=horses, form=form)


@page.route('/horses_sorted', methods=['GET', 'POST'])
def horses_sorted():
    form = HorseForm(request.form)
    horses = Horse.query.order_by(Horse.win_score)
    form.save(request.method)
    return render_template('horses.html', horses=horses, form=form)


@page.route('/horses_sorted_rev', methods=['GET', 'POST'])
def horses_sorted_rev():
    form = HorseForm(request.form)
    horses = Horse.query.order_by(Horse.win_score.desc())
    form.save(request.method)
    return render_template('horses.html', horses=horses, form=form)


@page.route('/jockeys', methods=['GET', 'POST'])
def jockeys():
    form = JockeyForm(request.form)
    jockeys = Jockey.query.all()
    form.save(request_method=request.method)
    return render_template('jockeys.html', jockeys=jockeys, form=form)


@page.route('/jockeys_sorted', methods=['GET', 'POST'])
def jockeys_sorted():
    form = JockeyForm(request.form)
    jockeys = Jockey.query.order_by(Jockey.win_score)
    form.save(request_method=request.method)
    return render_template('jockeys.html', jockeys=jockeys, form=form)


@page.route('/jockeys_sorted_rev', methods=['GET', 'POST'])
def jockeys_sorted_rev():
    form = JockeyForm(request.form)
    jockeys = Jockey.query.order_by(Jockey.win_score.desc())
    form.save(request_method=request.method)
    return render_template('jockeys.html', jockeys=jockeys, form=form)


@page.route('/events', methods=['GET', 'POST'])
def events():
    date_form = FindByDateForm(request.form)
    horses_form = FindByHorseForm(request.form)
    form = ParticipationForm(request.form)
    jockeys_form = FindByJockeyForm(request.form)

    partitipitions = Participition.query.join(Competition)

    if request.method == "POST":
        if date_form.date.data:
            partitipitions = Participition.query.join(Competition).filter(Competition.date == date_form.date.data,
                                                                          Participition.place == 1)
        if horses_form.horse.data:
            partitipitions = Participition.query.join(Competition).filter(Participition.horse == horses_form.horse.data)

        if jockeys_form.jockey.data:
            partitipitions = Participition.query.join(Competition).filter(Participition.jockey == jockeys_form.jockey.data)

        if form.data and form.validate_on_submit():
            form.save()

    return render_template('events.html', partitipitions=partitipitions, form=form, date_form=date_form,
                           horse_form=horses_form, jockeys_form=jockeys_form)

templates/base.html
<!doctype html>
<html lang="en">
    <head>
    {% block head %}
        <meta charset="utf-8">
        <link rel="stylesheet" href="/static/style.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    {% endblock %}
    </head>
<body>
  {% block navbar %}
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark d-flex justify-content-between fixed-top" >

        <!-- Brand/logo -->
  <a class="navbar-brand" href="#">
    <img src="https://w7.pngwing.com/pngs/210/469/png-transparent-horse-logo-silhouette-horse-animals-dog-like-mammal-monochrome.png" alt="logo" style="width:50px;">
  </a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('page.home_page') }}">Домашняя страница</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('page.horses') }}">Лошади</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('page.jockeys') }}">Наездники</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('page.events') }}">События</a>
    </li>
  </ul>

</nav>
   {% endblock %}
    {% block container %}
    {% endblock %}
</body>
</html>

templates/events.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
    {% block head %}
        <title>horses</title>
        {{ super() }}
    {% endblock %}
</head>

<body>
    {% block navbar %}
        {{ super() }}
    {% endblock %}

    {% block container %}
    <div class="container d-flex justify-content-around flex-wrap pt-6">
        <form method="POST">
            {{ date_form.date() }}
            {{ date_form.find }}
        </form>

        <form method="POST">
            {{ horse_form.horse }}
            {{ horse_form.submit }}
        </form>

        <form method="POST">
            {{ jockeys_form.jockey }}
            {{ jockeys_form.submit }}
        </form>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Место</th>
                    <th scope="col">Дата соревнования</th>
                    <th scope="col">Название ипподрома</th>
                    <th scope="col">Имя лошади</th>
                    <th scope="col">Имя наездника</th>
                </tr>
            </thead>
                <tbody>
                    {% for partitipition in partitipitions %}
                    <tr>
                            <td>{{ partitipition.place }}</td>
                            <td>{{ partitipition.competition.date }}</td>
                            <td>{{ partitipition.competition.hippodrome.name }}</td>
                            <td>{{ partitipition.horse.name }}</td>
                            <td>{{ partitipition.jockey.name }}</td>
                    </tr>
                     {% endfor %}
            </tbody>
        </table>
        <form method="POST">
            {{ form.csrf_token }}
            {{ form.place(class='form-control', placeholder='Место')}}
            {{ form.horse.label }}{{ form.horse(class='form-control form-control-lg') }}
            {{ form.jockey.label }}{{ form.jockey(class='form-control form-control-lg')  }}
            {{ form.competition.label }}{{ form.competition(class='form-control form-control-lg')  }}
            {{ form.submit(class="btn btn-lg btn-primary") }}
        </form>

    {% endblock %}
    </div>
</body>
</html>

templates/horses.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
    {% block head %}
        <title>horses</title>
        {{ super() }}
    {% endblock %}
</head>

<body>
    {% block navbar %}
        {{ super() }}
    {% endblock %}

    {% block container %}
    <div class="container d-flex justify-content-around flex-wrap pt-6">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('page.horses_sorted') }}">По возрастанию победы</a></li>
            <li class="breadcrumb-item"><a href="{{ url_for('page.horses_sorted_rev') }}">По убыванию победы</a></li>
          </ol>
        </nav>

        <table class="table">
              <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col">Имя лошади</th>
                  <th scope="col">Возраст лошади</th>
                  <th scope="col">Колличиство побед</th>
                  <th scope="col">Масть</th>
                </tr>
              </thead>
              <tbody>
              {% for horse in horses %}
                <tr>
                  <th scope="row">{{ horse.id }}</th>
                  <td>{{horse.name}}</td>
                  <td>{{ horse.age }}</td>
                  <td>{{ horse.win_score }}</td>
                  <td>{{ horse.suit }}</td>
                </tr>
              {% endfor %}
              </tbody>
        </table>
    </div>
    <form method="POST">
        <div class="form-group">
            {{ form.name.label }} {{ form.name(class='form-control') }}
            {{ form.age.label }}{{ form.age(class='form-control') }}
            {{ form.jockey.label }}{{ form.jockey(class='form-control form-control-lg')}}
            {{ form.suit.label}} {{ form.suit}}
            {{ form.submit(class="btn btn-lg btn-primary") }}
        </div>
    </form>
    {% endblock %}
</body>
</html>

templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
    {% block head %}
        <title>home</title>
        {{ super() }}
    {% endblock %}
</head>
<body>
  <!--==============================header=================================-->
{% block navbar %}
    {{ super() }}
{% endblock %}
  <!--==============================content================================-->
    {% block container %}
    <div class="container d-flex justify-content-around flex-wrap pt-6">

    </div>
  {% endblock %}
<!--==============================footer=================================-->
</body>
</html>

templates/jockeys.html
<!DOCTYPE html>
{% extends "base.html" %}
<html lang="en">
<head>
    {% block head %}
        <title>horses</title>
        {{ super() }}
    {% endblock %}
</head>

<body>
    {% block navbar %}
        {{ super() }}
    {% endblock %}

    {% block container %}
    <div class="container d-flex justify-content-around pt-6 flex-wrap pt-6">
        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('page.jockeys_sorted') }}">По возрастанию победы</a></li>
            <li class="breadcrumb-item"><a href="{{ url_for('page.jockeys_sorted_rev') }}">По убыванию победы</a></li>
          </ol>
        </nav>
           <table class="table">
              <thead>
                <tr>
                  <th scope="col"></th>
                  <th scope="col">Имя наездника</th>
                  <th scope="col">Возраст наездника</th>
                  <th scope="col">Колличиство побед</th>
                </tr>
              </thead>
              <tbody>
              {% for jockey in jockeys %}
                <tr>
                  <th scope="row">{{ jockey.id }}</th>
                  <td>{{jockey.name}}</td>
                  <td>{{ jockey.age }}</td>
                  <td>{{ jockey.win_score }}</td>
                </tr>
              {% endfor %}
              </tbody>
        </table>
    </div>
        <form method="POST">
            <div class="form-group">
                <label for="exampleInputEmail1">{{ form.name.label }}</label>
                 {{ form.name(class='form-control pt-2') }}
                {{ form.age.label }}{{ form.age(class='form-control pt-2') }}
                {{ form.submit(class="btn btn-lg btn-primary pt-2") }}
            </div>
        </form>
    {% endblock %}
</body>
</html>